[project]
name = "boldi-devmetapackage"
version = "0.1.0"
description = "Development Metapackage for Boldi's Python libraries"
authors = [
    {name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com"},
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

dependencies = []

[project.optional-dependencies]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "-e boldi @ file:///${PROJECT_ROOT}/pkg/boldi",
    "-e boldi-cli @ file:///${PROJECT_ROOT}/pkg/boldi-cli",
    "-e boldi-ctx @ file:///${PROJECT_ROOT}/pkg/boldi-ctx",
    "-e boldi-dev @ file:///${PROJECT_ROOT}/pkg/boldi-dev",
    "-e boldi-plugins @ file:///${PROJECT_ROOT}/pkg/boldi-plugins",
    "-e boldi-run @ file:///${PROJECT_ROOT}/pkg/boldi-run",
    "pdm",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "I", # sort imports
]