[project]
name = "boldi-devmetapackage"
description = "Development Metapackage for Boldi's Python libraries"
authors = [
    { name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com" },
]
requires-python = ">=3.9"
readme = "README.md"
license = { file = "LICENSE" }
dynamic = ["version"]

# Intentionally no dependencies as this is just a development metapackage.
# this just includes the real packages (boldi, boldi-cli, etc.) as dev-dependencies,
# and those packages can include real dependencies, including on each other.
dependencies = []

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build]
packages = ["."]

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    # boldi:
    "-e boldi @ {root:uri}/pkg/boldi",
    "-e boldi-cli @ {root:uri}/pkg/boldi-cli",
    "-e boldi-ctx @ {root:uri}/pkg/boldi-ctx",
    "-e boldi-dev @ {root:uri}/pkg/boldi-dev",
    "-e boldi-plugins @ {root:uri}/pkg/boldi-plugins",
    "-e boldi-proc @ {root:uri}/pkg/boldi-proc",
    # docs
    "mkdocs-autorefs",
    "mkdocs-material",
    "mkdocstrings[python]",
    # building and packaging:
    "pdm",
    "hatch",
    "hatchling",
    "hatch-vcs",
    "build",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "I", # sort imports
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["boldi", "boldi.*"]


[tool.pyright]
venvPath = "."
venv = ".venv"
