[project]
name = "boldi-devmetapackage"
version = "0.1.1"
description = "Development Metapackage for Boldi's Python libraries"
authors = [
    { name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com" },
]
requires-python = ">=3.9"
readme = "README.md"
license = { file = "LICENSE" }

# Intentionally no dependencies as this is just a development metapackage.
# this just includes the real packages (boldi, boldi-cli, etc.) as dev-dependencies,
# and those packages can include real dependencies, including on each other.
dependencies = []
optional-dependencies = {}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["boldi"]

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    # boldi:
    "-e boldi @ {root:uri}/pkg/boldi",
    "-e boldi-cli @ {root:uri}/pkg/boldi-cli",
    "-e boldi-ctx @ {root:uri}/pkg/boldi-ctx",
    "-e boldi-dev @ {root:uri}/pkg/boldi-dev",
    "-e boldi-plugins @ {root:uri}/pkg/boldi-plugins",
    # docs
    "mkdocs-autorefs",
    "mkdocs-material",
    "mkdocstrings[python]",
    # building and packaging:
    "pdm",
    "hatchling",
    "build",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "I", # sort imports
]

[tool.pyright]
venvPath = "."
venv = ".venv"
