[project]
name = "boldi-devmetapackage"
version = "0.1.0"
description = "Development Metapackage for Boldi's Python libraries"
authors = [
    {name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com"},
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

# Intentionally no dependencies as this is just a development metapackage.
# this just includes the real packages (boldi, boldi-cli, etc.) as dev-dependencies,
# and those packages can include real dependencies, including on each other.
dependencies = []
optional-dependencies = {}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    # this monorepo:
    "-e boldi @ file:///${PROJECT_ROOT}/pkg/boldi",
    "-e boldi-cli @ file:///${PROJECT_ROOT}/pkg/boldi-cli",
    "-e boldi-ctx @ file:///${PROJECT_ROOT}/pkg/boldi-ctx",
    "-e boldi-dev @ file:///${PROJECT_ROOT}/pkg/boldi-dev",
    "-e boldi-plugins @ file:///${PROJECT_ROOT}/pkg/boldi-plugins",
    "-e boldi-proc @ file:///${PROJECT_ROOT}/pkg/boldi-proc",
    # building and packaging:
    "pdm",
    "pdm-backend",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "I", # sort imports
]