[project]
name = "boldi-devmetapackage"
version = "0.1.0"
description = "Development Metapackage for Boldi's Python libraries"
authors = [
    {name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com"},
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

dependencies = []

[project.optional-dependencies]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "-e boldi @ file:///${PROJECT_ROOT}/pkg/boldi",
    "-e boldi-cli @ file:///${PROJECT_ROOT}/pkg/cli",
    "-e boldi-ctx @ file:///${PROJECT_ROOT}/pkg/ctx",
    "-e boldi-dev @ file:///${PROJECT_ROOT}/pkg/dev",
    "-e boldi-plugins @ file:///${PROJECT_ROOT}/pkg/plugins",
    "-e boldi-run @ file:///${PROJECT_ROOT}/pkg/run",
    "pdm",
]
