[project]
name = "boldi-ctx"
version = "0.1.0"
description = "boldi.ctx part of Boldi's Python libraries"
authors = [
    {name = "Boldizsár Palotás", email = "boldizsar.palotas@gmail.com"},
]
requires-python = ">=3.9"
readme = "../../README.md"
license = {text = "MIT"}

dependencies = [
    "typing_extensions",
]

[project.optional-dependencies]
# extra1 = ["flask"]
# extra2 = ["django"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]

[tool.pdm.dev-dependencies]
# dev1 = ["pytest"]
# dev2 = ["mkdocs"]

[tool.pdm.build]
includes = ["../../boldi", "../../boldi/ctx.py"]
excludes = ["../../boldi/*"]
# source-includes = []
